### ISSUE TITLE
ImportError: cannot import name 'AssertHTMLMixin' from 'with_asserts'

### ISSUE THREAD

**Issue by khpeek** [johnpaulett/django-with-asserts#5]
I've created a new Django project in Python 3.7.3 and at the top of `tests.py` simply added the following two imports:

```python
from django.test import TestCase
from with_asserts import AssertHTMLMixin
```
However, if I try to run the tests using
```
python manage.py test
```
I get the following error message:
```
> python manage.py test
System check identified no issues (0 silenced).
E
======================================================================
ERROR: myapp.tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: myapp.tests
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/kurtpeek/Documents/myproject/myapp/tests.py", line 2, in <module>
    from with_asserts import AssertHTMLMixin
ImportError: cannot import name 'AssertHTMLMixin' from 'with_asserts' (/Users/kurtpeek/.local/share/virtualenvs/Documents-8egWPGwQ/lib/python3.7/site-packages/with_asserts/__init__.py)


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```
It seems that this somehow leads to a circular import? How can I fix this and import the `AssertHTMLMixin`?

**Comment by khpeek** [comment]
It turns out that you have to import the mix-in like so:
```python
from with_asserts.mixin import AssertHTMLMixin
```
This is not how the package is documented at https://django-with-asserts.readthedocs.io/en/latest/#usage, however:

![image](https://user-images.githubusercontent.com/6617594/60736326-6df8f680-9f0b-11e9-9b50-e16baef0c33e.png)

Perhaps the `AssertHTMLMixin` should be exposed at the top level so that the package works as documented?
